name: constrained_sps
version: 0.0.4
description: Constraint Satisfaction Problem Solver for Dart
homepage: https://github.com/davecom/constraineD

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0